### PR TITLE
use OAuth for tidalapi/python-tidal

### LINKED ISSUE #1: ERROR: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username
Could there be an issue with usernames that include a plus sign?
```
python3 main.py --backup --user "SPDurkee+Tidal20220110@gmail.com" --password "XXXXXXX"
Namespace(backup=True, filename=None, password='XXXXXX', restore=False, user='SPDurkee+Tidal20220110@gmail.com')
{"status":401,"subStatus":8003,"userMessage":"Client not found"}
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(sys.argv[1:])
  File "main.py", line 80, in main
    session.login(args_parsed.user, args_parsed.password)
  File "/home/simon/.local/lib/python3.8/site-packages/tidalapi/__init__.py", line 198, in login
    request.raise_for_status()
  File "/home/simon/.local/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username
```

### PR DESCRIPTION
**Pull request by lpirl**
This would be my take on implementing/using OAuth for the Tidal API.
What do you think? Would fix #1.

### CODE REVIEW

**Comment by pepitooo** [comment]
I planned to do it but you did it.

It might be nice to store the config a file directly ?
Otherwise, well done, and thanks

**Comment by lpirl** [comment]
No worries, I just needed a way to backup my favs. :) So thanks for your code in the first place!

Yes I considered storing the credentials and it would of course be okay for me if someone implements this functionality. Personally, I decided against implementing this for this upstream PR since it would essential store credentials on disk without asking.

Oh and if you wonder why I chose an INI file over CLI arguments (or why the parameters cannot be provided via CLI): files are usually easy to protect against unauthorized access than CLI arguments (which are visible in `/proc`).

**Comment by pepitooo** [comment]
you are right for cli argument, as I was using it in a vm only started for tidal purposes, it was the easiest way to do.
But now with a token it's more safe anyway.

**Comment by lpirl** [comment]
Great, thanks for the discussion and merging instantly. Wow.

**Pull request merged**
